version: '3.8'

services:
  dyplom_project:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - automation
    depends_on:
      - db

  db:
    image: postgres
    hostname: db
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - automation

volumes:
  postgres_data:

networks:
  automation: