version: '3.8'

services:
#  dyplom_project:
#    build: .
#    command: >
#      sh -c "python manage.py collectstatic --noinput &&
#             python manage.py migrate &&
#             gunicorn netology_pg_diplom.wsgi:application --bind 0.0.0.0:8000"
#    expose:
#      - 8000
#    networks:
#      - automation
#    depends_on:
#      - db
#
#  db:
#    image: postgres
#    hostname: db
#    restart: always
#    environment:
#      - POSTRES_USER=$DB_USER
#      - POSTGRES_PASSWORD=$DB_PASSWORD
#      - POSTGRES_DB=$DB_NAME
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    networks:
#      - automation
#
#  nginx:
#    build: ./nginx
#    ports:
#      - 6060:80
#    depends_on:
#      - dyplom_project
#    volumes:
#      - ./static:/static
#    networks:
#      - automation

  redis:
    image: redis
    ports:
      - "6379:6379"
#    networks:
#      - automation
#volumes:
#  postgres_data:

#networks:
#  automation: