version: '3.8'

services:
  dyplom_project:
    build: .
    command: gunicorn netology_pg_diplom.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    networks:
      - automation
    depends_on:
      - db
#    entrypoint: ["/usr/src/product_automation/entrypoint.sh"]

  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      - POSTRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - automation

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - dyplom_project
    volumes:
      - ./static:/static
    networks:
      - automation

volumes:
  postgres_data:

networks:
  automation: