# Generated by Django 4.2.1 on 2023-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='building',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='structure',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
