# Generated by Django 4.2.1 on 2023-05-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_category_order_parameter_product_productinfo_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
