# Generated by Django 4.2.1 on 2023-05-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_shop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
