# Generated by Django 4.2.1 on 2023-06-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_orderitem_alter_customuser_managers_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
    ]
