# Generated by Django 4.2.1 on 2023-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_order_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, max_length=40, unique=True, verbose_name='Ссылка на сайт магазина'),
        ),
    ]
