# Generated by Django 4.2.1 on 2023-06-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_orderitem_quantity_alter_productinfo_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='productparameter',
            name='product_info',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(related_name='categories', to='backend.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(max_length=40, unique=True, verbose_name='Ссылка на сайт магазина'),
        ),
        migrations.DeleteModel(
            name='Orderitem',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Productinfo',
        ),
        migrations.DeleteModel(
            name='ProductParameter',
        ),
    ]
