# Generated by Django 4.2.1 on 2023-06-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_shop_filename_productinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='model',
        ),
    ]
